--
-- PostgreSQL database dump
--

\restrict TSOfPaWL4h1zMXuDMt8f9ARco1vxXgmhTGNHHShAYOE86gZaUgBHO6LopHLDz0G

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bank_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bank_accounts (
    id integer NOT NULL,
    balance integer NOT NULL,
    firstname character varying(100) NOT NULL,
    lastname character varying(100) NOT NULL,
    CONSTRAINT bank_accounts_balance_check CHECK ((balance >= 0))
);


ALTER TABLE public.bank_accounts OWNER TO postgres;

--
-- Name: bank_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bank_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    id integer NOT NULL,
    language_name character varying(100),
    language_level character varying(100),
    description text,
    teacher_id integer
);


ALTER TABLE public.courses OWNER TO postgres;

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    id integer NOT NULL,
    firstname character varying(100),
    lastname character varying(100),
    email character varying(100),
    age integer,
    course_id integer,
    payment_status character varying(50)
);


ALTER TABLE public.students OWNER TO postgres;

--
-- Name: students_copy; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students_copy (
    id integer NOT NULL,
    firstname character varying(100),
    lastname character varying(100),
    email character varying(100),
    age integer,
    course_id integer,
    payment_status character varying(50)
);


ALTER TABLE public.students_copy OWNER TO postgres;

--
-- Name: students_copy_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.students_copy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_copy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1
);


--
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teachers (
    id integer NOT NULL,
    firstname character varying(100),
    lastname character varying(100),
    email character varying(100)
);


ALTER TABLE public.teachers OWNER TO postgres;

--
-- Name: teachers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bank_accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bank_accounts (id, balance, firstname, lastname) FROM stdin;
1	3000	John	Schroeder
2	220	Bobby	Lynch
3	29000	Edward	Rice
4	47000	Keith	Cox
5	2000	Peter	Brandt
6	3200	Amber	Brown
7	2000	Paul	Campbell
8	8200	William	Rodgers
9	550	John	Smith
10	140	Tracey	Davis
11	9000	Kenneth	Dickerson
12	180	Michele	Hardy
13	20	Monica	Vazquez
14	200	Barbara	Morris
15	5600	Jessica	Hughes
16	8300	Dylan	Pierce
17	4600	Ashley	Taylor
18	850	Lawrence	Mcintosh
19	410	Michael	Bailey
20	900	John	Alvarado
21	1700	Nancy	Thomas
22	78000	Tamara	Flores
23	7000	Brenda	Shepard
24	540	Randall	Washington
25	1200	Connie	Mays
26	6900	Holly	Gray
27	1500	Terri	Lyons
28	7500	Patricia	Cline
29	5000	Joseph	Clark
30	8800	John	Adams
31	34000	Jennifer	Willis
32	58000	Cindy	Bowers
33	680	Amy	Gentry
34	740	Evan	Mcintyre
35	2300	Jeremy	May
36	8200	Michael	Hester
37	69000	Dawn	Chang
38	29000	Steven	Cantrell
39	54000	Michelle	Harding
40	810	Timothy	Hicks
41	27000	Jason	Montoya
42	250	Rhonda	Fisher
43	820	Dwayne	Roach
44	730	Nancy	Grant
45	380	Amy	Hoffman
46	55000	Elaine	Torres
47	43000	Susan	Thompson
48	690	Edward	Parker
49	7600	Alicia	Hall
50	4900	Lisa	Bauer
\.


--
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses (id, language_name, language_level, description, teacher_id) FROM stdin;
1	Spanish	1	Welcome to our Spanish for Beginners course, an engaging and interactive journey designed for those starting their adventure with the Spanish language. This course provides a solid foundation in basic Spanish, focusing on essential vocabulary, grammar, and pronunciation. Through a series of practical exercises and immersive activities, students will learn to communicate in everyday situations such as introducing themselves, ordering food, asking for directions, and shopping. The course also introduces key aspects of Hispanic culture, allowing students to gain a cultural context for the language. Our experienced instructors employ a variety of teaching methods to ensure a fun and supportive learning environment. By the end of this course, students will be able to understand and use familiar everyday expressions and participate in simple conversations, setting the stage for further Spanish studies and real-world application.	3
2	German	1	Welcome to our German Language for Beginners course! This course is designed for individuals who have little to no background in German. Through a combination of interactive lessons, engaging activities, and practical applications, you will start your journey to fluency in German. Our experienced instructors will guide you through the basics of German grammar, vocabulary, and pronunciation, ensuring a solid foundation for your language learning journey.	3
3	French	1	Our French for Beginners course offers an engaging introduction to the French language, tailored for those with little to no prior experience. This course lays the foundation for understanding and using basic French, focusing on key areas such as pronunciation, essential vocabulary, and fundamental grammatical structures. Students will learn how to construct simple sentences and engage in basic conversations, covering everyday topics like greetings, self-introductions, asking for directions, and ordering food. The course also introduces elements of French culture, providing a richer context for the language. Interactive exercises and practical activities are designed to build confidence in speaking, listening, reading, and writing in French. By the end of the course, students will be equipped with the skills to communicate effectively in basic French and have a solid foundation for future language development.	1
4	Chinese	1	Our Chinese for Beginners course offers an exciting introduction to Mandarin Chinese, the most widely spoken language in the world. Designed for those with little to no background in Chinese, this course focuses on the essentials of pronunciation, basic vocabulary, and fundamental sentence structures. You will learn key phrases for everyday communication, including greetings, introductions, and simple questions and answers. The course also introduces the basics of Chinese characters, providing a foundation for reading and writing. Emphasis is placed on Pinyin (the Romanization system for Chinese), tones, and basic grammar to ensure a strong foundational understanding. Cultural insights are integrated throughout the course to enhance learning and appreciation of the Chinese language. By the end of this course, students will be able to engage in simple conversations and have a solid base for further Chinese language study.	5
5	Spanish	2	Our Spanish Intermediate course is tailored for learners who have a foundational understanding of Spanish and aim to elevate their proficiency. This course deepens your grasp of Spanish grammar, enriches your vocabulary, and enhances your conversational skills. You will engage with a variety of authentic Spanish texts and media, helping you to understand diverse dialects and cultural nuances. The course emphasizes practical language use, enabling you to navigate complex scenarios such as expressing opinions, making plans, and discussing current events. Interactive activities and discussions will encourage you to use Spanish more fluently and confidently in both personal and professional contexts. By the end of this course, you will have a comprehensive understanding of intermediate Spanish, preparing you for advanced language challenges or real-world Spanish-speaking experiences.	4
6	German	2	Our German Intermediate course is designed for learners who have a basic understanding of the German language and are looking to advance their proficiency. This course focuses on enhancing your grammatical knowledge, expanding your vocabulary, and improving your ability to communicate in more complex and nuanced situations. You will engage in interactive lessons that delve deeper into the German language, exploring various themes and topics relevant to everyday life in a German-speaking environment. Through a mix of reading, writing, listening, and speaking exercises, you will develop greater fluency and confidence in using German in both personal and professional contexts. The course also emphasizes cultural understanding, helping you to navigate and appreciate the rich tapestry of German-speaking societies. By the end of this course, you will be well-equipped to express yourself more effectively and understand the subtleties of the German language, paving the way for advanced learning or professional opportunities.	5
7	French	2	Our French Intermediate course is designed for learners who have a foundational grasp of French and are ready to elevate their language skills. This engaging program delves into more complex grammatical structures and enriches your vocabulary, enabling you to engage confidently in a broader range of conversations. You will explore various intermediate topics, including French culture, arts, and current events, enhancing your ability to discuss these subjects with depth and nuance. The course emphasizes practical language use, sharpening your listening, speaking, reading, and writing abilities through a blend of classroom discussions, multimedia resources, and real-life scenarios. You will also refine your pronunciation and comprehension skills, preparing you for more advanced linguistic challenges. By the end of this course, you will have a heightened understanding of the French language, allowing for more fluid communication and a deeper appreciation of the Francophone world.	3
8	Chinese	2	Our Intermediate Chinese course is designed for students who have a basic understanding of Mandarin and are ready to further enhance their language skills. This course delves deeper into more complex grammatical structures and expands your vocabulary, enabling you to converse on a wider range of topics. You will improve your listening and speaking skills through interactive dialogues and real-life scenarios, such as discussing hobbies, travel experiences, and current events. The course also emphasizes reading and writing, with a focus on understanding and using Chinese characters in various contexts. You will learn to express your thoughts more clearly and accurately, both verbally and in writing. Cultural nuances and idiomatic expressions are integrated into the lessons, providing a richer understanding of Chinese culture and language. By the end of this course, you will be equipped to communicate more confidently and effectively in Mandarin, setting a strong foundation for advanced studies or professional use.	5
\.


--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.students (id, firstname, lastname, email, age, course_id, payment_status) FROM stdin;
1	Joshua	Walters	greg43@hotmail.com	70	3	PENDING
2	David	Pratt	ewilliams@gmail.com	54	\N	PAID
3	Kimberly	Carroll	leslie90@gmail.com	35	8	PENDING
4	Deborah	Cain	rzhang@yahoo.com	44	8	PENDING
5	William	Davis	melinda79@gmail.com	43	3	PENDING
6	Kristen	Valenzuela	shughes@yahoo.com	46	6	PENDING
7	Mary	Lindsey	brandon17@hotmail.com	20	1	PAID
8	Jeremy	Bradley	rebeccabenson@gmail.com	77	4	PAID
9	Katelyn	Thompson	roserivera@hotmail.com	19	2	REJECTED
10	Nicole	Sanchez	mcdowellshawn@gmail.com	68	3	PAID
11	Caleb	Gallegos	darrell52@gmail.com	28	8	PENDING
12	Yvonne	Wright	ipowell@gmail.com	34	1	PENDING
13	Hector	King	ryan81@hotmail.com	35	7	REJECTED
14	Alexandra	Dillon	laurenharmon@hotmail.com	39	7	REJECTED
15	Sarah	Garcia	hillbrian@gmail.com	29	5	PAID
16	Yolanda	Walker	karengonzalez@gmail.com	58	7	PAID
17	Taylor	Diaz	jesseturner@yahoo.com	19	6	REJECTED
18	Jose	Bennett	jeremy79@gmail.com	52	3	REJECTED
19	Karen	Frazier	robersonelaine@gmail.com	44	\N	PENDING
20	Timothy	Anderson	kbest@yahoo.com	57	5	PAID
21	Laura	Parsons	charlescollins@hotmail.com	35	5	REJECTED
22	George	Luna	jasminemiller@yahoo.com	47	6	PENDING
23	Ricky	Santana	bentleydenise@hotmail.com	37	6	REJECTED
24	Jose	Reynolds	jennifer47@hotmail.com	62	3	PAID
25	Michelle	Richardson	tcook@hotmail.com	56	8	PENDING
26	Alexander	Lozano	thomas00@gmail.com	94	5	REJECTED
27	Mark	Cortez	racheljones@yahoo.com	22	1	REJECTED
28	Caroline	Herrera	pgonzalez@gmail.com	100	8	PENDING
29	Sharon	Sullivan	nbaker@hotmail.com	41	5	PENDING
30	Natalie	Nelson	jennahurst@yahoo.com	72	8	PENDING
31	Jennifer	Estrada	myerscynthia@gmail.com	23	\N	PENDING
32	Joseph	Williams	icruz@yahoo.com	87	5	PENDING
33	Trevor	Salinas	veronicagutierrez@gmail.com	95	5	PAID
34	Jennifer	Chavez	derekgomez@gmail.com	37	5	PENDING
35	Rodney	Gallegos	michael90@hotmail.com	48	2	PAID
36	Connie	Smith	coxkaren@gmail.com	33	2	PAID
37	Alicia	Johnson	hawkinsluke@yahoo.com	63	4	PAID
38	Cynthia	Armstrong	sean86@yahoo.com	44	8	PENDING
39	Sean	Gray	qbass@hotmail.com	33	3	REJECTED
40	Jacob	Anderson	smithbrandon@yahoo.com	85	\N	PENDING
41	Alex	Johnson	elizabeth39@hotmail.com	85	\N	PENDING
42	Robert	Richardson	cheryljohnson@hotmail.com	50	7	PAID
43	Angela	Thompson	lwilliams@hotmail.com	73	8	PENDING
44	Kyle	Cole	emily54@gmail.com	60	7	REJECTED
45	Erin	Moody	pamrich@yahoo.com	30	5	PAID
46	Julie	Rivera	hawkinsbrenda@yahoo.com	54	8	PENDING
47	Julie	Hughes	nshaw@hotmail.com	70	4	PAID
48	Kayla	Johnson	andresdawson@hotmail.com	21	5	REJECTED
49	Tanya	Weber	williamhernandez@gmail.com	51	7	REJECTED
50	Patrick	Ellis	ylopez@yahoo.com	54	2	PENDING
51	Alvin	Wiggins	joseph67@yahoo.com	47	7	PAID
52	Tami	Mata	susanortiz@gmail.com	70	6	PENDING
53	Kevin	Wilson	elizabeth32@yahoo.com	41	1	PENDING
54	Dakota	Serrano	emilyallen@gmail.com	45	4	PAID
55	David	Allen	gary91@gmail.com	93	5	PENDING
56	Kara	Moreno	donaldstewart@gmail.com	86	2	PAID
57	Spencer	Mckinney	ingramnicole@yahoo.com	25	4	PAID
58	Doris	Edwards	riversheather@hotmail.com	33	\N	PENDING
59	Christopher	Ball	akline@hotmail.com	24	1	PENDING
60	Samuel	Roth	william74@hotmail.com	64	\N	REJECTED
61	Carrie	Spears	jack09@gmail.com	21	7	PAID
62	Alejandro	Mooney	lynnvaughan@yahoo.com	30	7	PENDING
63	Karen	Wheeler	jeremy61@yahoo.com	52	8	PENDING
64	Theresa	Davis	jasmindiaz@gmail.com	93	7	PENDING
65	Devin	Morris	virginiakelly@hotmail.com	33	2	REJECTED
66	Corey	Woods	wolfekaren@yahoo.com	55	1	PENDING
67	Deborah	Ruiz	nelsonrobert@gmail.com	64	2	REJECTED
68	James	Moore	syates@hotmail.com	80	7	PENDING
69	Amanda	Morris	ncarter@hotmail.com	21	5	PAID
70	Cynthia	Farmer	tferguson@gmail.com	28	\N	PENDING
71	Carl	Lewis	william66@hotmail.com	58	6	PENDING
72	Angela	Coleman	ejohnson@hotmail.com	57	7	PAID
73	Frank	Krause	andrewatkins@yahoo.com	24	8	PENDING
74	Nicolas	Coleman	jamesmiller@yahoo.com	82	7	PAID
75	Christine	Jenkins	rickytucker@yahoo.com	27	1	PAID
76	Sarah	Gutierrez	deannafischer@gmail.com	52	2	PAID
77	Michael	Hunter	kendraroberts@gmail.com	25	7	PENDING
78	Emily	Raymond	victoria22@gmail.com	59	\N	PENDING
79	Caitlin	Hoffman	samuelharmon@gmail.com	24	7	PAID
80	Matthew	Rice	qwatson@gmail.com	74	\N	REJECTED
81	Emily	Harris	michaelacosta@hotmail.com	43	5	PAID
82	Aaron	Martinez	norrismiranda@hotmail.com	19	5	PAID
83	Belinda	Mata	evanssergio@yahoo.com	44	1	REJECTED
84	Jodi	Duarte	juanhamilton@yahoo.com	60	\N	PENDING
85	Stacey	Wong	jamie02@yahoo.com	70	3	PENDING
86	Brandon	Hughes	jacob15@gmail.com	91	6	REJECTED
87	Rachel	Mills	hking@yahoo.com	31	2	PAID
88	Paul	Brown	amy25@yahoo.com	27	8	PENDING
89	Vincent	Greene	johnstondiana@gmail.com	31	6	REJECTED
90	Lindsey	Knight	stevenscolleen@yahoo.com	27	4	PAID
91	Steven	Ramirez	lmalone@gmail.com	53	2	PENDING
92	Sean	Curry	laurenjohnson@yahoo.com	60	5	REJECTED
93	Maria	Woodward	iwhite@hotmail.com	36	6	REJECTED
94	Patrick	Mathews	anthony24@yahoo.com	33	\N	PENDING
95	Andrew	Tanner	qmullins@hotmail.com	82	6	PENDING
96	Jordan	Murillo	fcombs@gmail.com	75	5	PAID
97	Victoria	Turner	maria36@gmail.com	20	\N	REJECTED
98	Angela	Smith	mcdonaldjodi@yahoo.com	77	5	REJECTED
99	William	Phelps	moralesdavid@yahoo.com	59	3	PAID
100	Christopher	Hayes	deancheryl@yahoo.com	33	\N	PENDING
101	Danielle	Kelly	anne28@gmail.com	94	6	PAID
102	Rebekah	Smith	estone@hotmail.com	55	2	PENDING
103	Sarah	Benjamin	steven27@gmail.com	18	\N	PAID
104	Robert	Schultz	drodgers@yahoo.com	57	8	PENDING
105	Darryl	Oliver	melvin19@hotmail.com	43	3	PENDING
106	Alyssa	Finley	martingary@yahoo.com	94	5	PENDING
107	Lisa	Keith	kathleenlopez@gmail.com	38	\N	PENDING
108	Monica	Smith	williamestes@hotmail.com	41	5	REJECTED
109	Crystal	Burgess	taylorpeter@hotmail.com	37	2	PAID
110	Henry	Wall	wmerritt@hotmail.com	89	2	PAID
111	Brittany	Gomez	keith40@yahoo.com	55	8	PENDING
112	Kenneth	Bell	maryhogan@yahoo.com	49	3	PENDING
113	Daniel	Simmons	hknapp@yahoo.com	60	6	REJECTED
114	Christine	Santana	joshua28@gmail.com	80	1	PENDING
115	Anne	Russell	omiller@hotmail.com	45	5	REJECTED
116	Jenna	Robertson	alanvazquez@yahoo.com	21	7	PAID
117	Brandy	Schneider	combskevin@yahoo.com	70	1	PENDING
118	Robert	Stephens	stonekathleen@gmail.com	30	5	REJECTED
119	Jeffrey	Brown	cindy33@gmail.com	47	3	REJECTED
120	George	Blair	justin62@gmail.com	60	2	REJECTED
121	Tamara	Davis	andersonaaron@yahoo.com	44	4	PAID
122	Nicholas	Haley	smithmichael@gmail.com	54	7	PAID
123	Ryan	James	sandra90@yahoo.com	20	2	PENDING
124	Emily	White	vsmith@hotmail.com	34	\N	REJECTED
125	Joanna	Pearson	paulwebb@gmail.com	19	4	PAID
126	Marcia	Skinner	austinkim@gmail.com	47	4	PAID
127	Steven	Callahan	armstrongdouglas@gmail.com	75	5	PENDING
128	Joshua	Cline	harrishannah@yahoo.com	96	7	REJECTED
129	Amber	Morton	sgordon@yahoo.com	64	\N	PAID
130	Allison	Liu	rrobinson@gmail.com	61	7	REJECTED
131	Karen	Allen	heather66@yahoo.com	19	\N	PAID
132	Kristen	Rodriguez	laceyjohnston@gmail.com	63	8	PENDING
133	Bobby	Rogers	maryrivera@gmail.com	58	\N	REJECTED
134	Allen	Johnson	fieldssusan@gmail.com	55	5	PAID
135	Nicole	Wallace	candicemoreno@gmail.com	38	\N	PAID
136	Kyle	Davis	johnwise@hotmail.com	54	8	PENDING
137	Miguel	Austin	thomasadam@gmail.com	41	6	REJECTED
138	Nicholas	Jones	parkersusan@yahoo.com	86	5	PENDING
139	Katrina	Welch	psmith@yahoo.com	19	\N	PAID
140	Sandra	Walker	iclay@hotmail.com	61	5	REJECTED
141	Brian	Espinoza	flopez@hotmail.com	50	8	PENDING
142	Denise	Martin	kristina00@yahoo.com	42	\N	REJECTED
143	Karina	Sutton	baxterbradley@gmail.com	35	8	PENDING
144	Stephanie	Myers	jramos@gmail.com	68	\N	PAID
145	Michael	Lane	donna42@yahoo.com	19	6	PENDING
146	Christine	Elliott	vbell@hotmail.com	45	2	REJECTED
147	Kristin	Chung	vwatkins@yahoo.com	43	5	PENDING
148	Melissa	Doyle	qhoward@gmail.com	92	5	REJECTED
149	Leslie	Parker	turnersherri@yahoo.com	48	7	PAID
150	Robin	Burke	mlewis@gmail.com	27	1	REJECTED
151	Jeffrey	Smith	mallory08@hotmail.com	30	7	PAID
152	Corey	Harris	wagnerjames@hotmail.com	77	2	REJECTED
153	Johnny	Hall	chris73@gmail.com	22	7	PENDING
154	Mary	King	hodgejennifer@hotmail.com	100	5	PENDING
155	Katie	Payne	shubbard@hotmail.com	46	2	PENDING
156	Alexis	Garcia	patrickjohnson@hotmail.com	19	4	PAID
157	Timothy	Weaver	eshelton@yahoo.com	48	\N	REJECTED
158	Danny	Boone	anathompson@hotmail.com	23	3	PAID
159	Jessica	Powell	tammy25@yahoo.com	43	5	REJECTED
160	Robert	Goodman	webbmelissa@hotmail.com	71	5	REJECTED
161	Terri	Scott	meyersmichael@yahoo.com	100	2	PENDING
162	Erica	Reed	taratodd@hotmail.com	32	7	REJECTED
163	Kenneth	Frey	zvaldez@hotmail.com	46	6	PAID
164	Tracy	Jackson	william25@yahoo.com	33	6	PENDING
165	Roy	Peterson	alancarr@gmail.com	39	2	PAID
166	William	Lopez	qbennett@gmail.com	74	6	REJECTED
167	Zachary	Bryant	haley00@gmail.com	29	2	REJECTED
168	Brandon	Romero	kirkdoyle@hotmail.com	80	6	PAID
169	Heather	Bailey	bhendricks@hotmail.com	60	8	PENDING
170	Kenneth	Wolfe	bpatrick@yahoo.com	48	5	PAID
171	Ryan	Brooks	hmartin@yahoo.com	32	7	PAID
172	Linda	Lang	johnsonashley@hotmail.com	34	3	REJECTED
173	Brittany	Snow	nancyreed@hotmail.com	35	4	PAID
174	David	Smith	scott04@gmail.com	88	8	PENDING
175	Brian	Hamilton	sandy92@hotmail.com	69	3	REJECTED
176	Joanne	Love	millspatricia@gmail.com	51	3	REJECTED
177	Misty	Palmer	maria36@gmail.com	33	5	REJECTED
178	Julie	Williams	adrianmiller@yahoo.com	59	7	PENDING
179	Tracey	Wells	daniel08@yahoo.com	48	5	PAID
180	Michael	Casey	amber41@gmail.com	31	1	REJECTED
181	Jeremy	Cruz	simmonschristian@hotmail.com	82	\N	REJECTED
182	Matthew	Reed	michaelgraham@gmail.com	22	7	REJECTED
183	Jaclyn	Warner	cdunn@hotmail.com	71	2	PENDING
184	Charles	Garcia	davidalexander@hotmail.com	53	8	PENDING
185	Leslie	Mejia	xgarrett@gmail.com	60	1	PAID
186	Nathan	Boyd	daniel86@gmail.com	56	8	PENDING
187	Frances	Robertson	daniellesantiago@hotmail.com	65	4	PAID
188	Melissa	Reynolds	uponce@gmail.com	48	6	PAID
189	Brenda	Hughes	oking@gmail.com	59	8	PENDING
190	Gabriel	Bell	jessicajones@yahoo.com	43	\N	PENDING
191	Eric	Ortiz	joneskristen@gmail.com	29	4	PAID
192	Cheryl	Smith	tracy41@gmail.com	92	8	PENDING
193	Jeffrey	Ruiz	brenda19@gmail.com	41	5	REJECTED
194	Dustin	Wolfe	jackie18@yahoo.com	54	7	PENDING
195	Zachary	Smith	blackerika@gmail.com	45	2	REJECTED
196	Victor	Phillips	theresa80@gmail.com	43	1	REJECTED
197	Jennifer	Flores	hmathis@hotmail.com	48	4	PAID
198	Michael	Bullock	ryan52@hotmail.com	28	2	PAID
199	Melissa	Leon	zandrade@yahoo.com	40	5	PAID
200	Angela	Rogers	reneediaz@yahoo.com	98	2	PAID
\.


--
-- Data for Name: students_copy; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.students_copy (id, firstname, lastname, email, age, course_id, payment_status) FROM stdin;
203	Joshua	Walters	greg43@hotmail.com	70	3	PENDING
204	David	Pratt	ewilliams@gmail.com	54	\N	PAID
205	Kimberly	Carroll	leslie90@gmail.com	35	8	PENDING
206	Deborah	Cain	rzhang@yahoo.com	44	8	PENDING
207	William	Davis	melinda79@gmail.com	43	3	PENDING
208	Kristen	Valenzuela	shughes@yahoo.com	46	6	PENDING
209	Mary	Lindsey	brandon17@hotmail.com	20	1	PAID
210	Jeremy	Bradley	rebeccabenson@gmail.com	77	4	PAID
211	Katelyn	Thompson	roserivera@hotmail.com	19	2	REJECTED
212	Nicole	Sanchez	mcdowellshawn@gmail.com	68	3	PAID
213	Caleb	Gallegos	darrell52@gmail.com	28	8	PENDING
214	Yvonne	Wright	ipowell@gmail.com	34	1	PENDING
215	Hector	King	ryan81@hotmail.com	35	7	REJECTED
216	Alexandra	Dillon	laurenharmon@hotmail.com	39	7	REJECTED
217	Sarah	Garcia	hillbrian@gmail.com	29	5	PAID
218	Yolanda	Walker	karengonzalez@gmail.com	58	7	PAID
219	Taylor	Diaz	jesseturner@yahoo.com	19	6	REJECTED
220	Jose	Bennett	jeremy79@gmail.com	52	3	REJECTED
221	Karen	Frazier	robersonelaine@gmail.com	44	\N	PENDING
222	Timothy	Anderson	kbest@yahoo.com	57	5	PAID
223	Laura	Parsons	charlescollins@hotmail.com	35	5	REJECTED
224	George	Luna	jasminemiller@yahoo.com	47	6	PENDING
225	Ricky	Santana	bentleydenise@hotmail.com	37	6	REJECTED
226	Jose	Reynolds	jennifer47@hotmail.com	62	3	PAID
227	Michelle	Richardson	tcook@hotmail.com	56	8	PENDING
228	Alexander	Lozano	thomas00@gmail.com	94	5	REJECTED
229	Mark	Cortez	racheljones@yahoo.com	22	1	REJECTED
230	Caroline	Herrera	pgonzalez@gmail.com	100	8	PENDING
231	Sharon	Sullivan	nbaker@hotmail.com	41	5	PENDING
232	Natalie	Nelson	jennahurst@yahoo.com	72	8	PENDING
233	Jennifer	Estrada	myerscynthia@gmail.com	23	\N	PENDING
234	Joseph	Williams	icruz@yahoo.com	87	5	PENDING
235	Trevor	Salinas	veronicagutierrez@gmail.com	95	5	PAID
236	Jennifer	Chavez	derekgomez@gmail.com	37	5	PENDING
237	Rodney	Gallegos	michael90@hotmail.com	48	2	PAID
238	Connie	Smith	coxkaren@gmail.com	33	2	PAID
239	Alicia	Johnson	hawkinsluke@yahoo.com	63	4	PAID
240	Cynthia	Armstrong	sean86@yahoo.com	44	8	PENDING
241	Sean	Gray	qbass@hotmail.com	33	3	REJECTED
242	Jacob	Anderson	smithbrandon@yahoo.com	85	\N	PENDING
243	Alex	Johnson	elizabeth39@hotmail.com	85	\N	PENDING
244	Robert	Richardson	cheryljohnson@hotmail.com	50	7	PAID
245	Angela	Thompson	lwilliams@hotmail.com	73	8	PENDING
246	Kyle	Cole	emily54@gmail.com	60	7	REJECTED
247	Erin	Moody	pamrich@yahoo.com	30	5	PAID
248	Julie	Rivera	hawkinsbrenda@yahoo.com	54	8	PENDING
249	Julie	Hughes	nshaw@hotmail.com	70	4	PAID
250	Kayla	Johnson	andresdawson@hotmail.com	21	5	REJECTED
251	Tanya	Weber	williamhernandez@gmail.com	51	7	REJECTED
252	Patrick	Ellis	ylopez@yahoo.com	54	2	PENDING
253	Alvin	Wiggins	joseph67@yahoo.com	47	7	PAID
254	Tami	Mata	susanortiz@gmail.com	70	6	PENDING
255	Kevin	Wilson	elizabeth32@yahoo.com	41	1	PENDING
256	Dakota	Serrano	emilyallen@gmail.com	45	4	PAID
257	David	Allen	gary91@gmail.com	93	5	PENDING
258	Kara	Moreno	donaldstewart@gmail.com	86	2	PAID
259	Spencer	Mckinney	ingramnicole@yahoo.com	25	4	PAID
260	Doris	Edwards	riversheather@hotmail.com	33	\N	PENDING
261	Christopher	Ball	akline@hotmail.com	24	1	PENDING
262	Samuel	Roth	william74@hotmail.com	64	\N	REJECTED
263	Carrie	Spears	jack09@gmail.com	21	7	PAID
264	Alejandro	Mooney	lynnvaughan@yahoo.com	30	7	PENDING
265	Karen	Wheeler	jeremy61@yahoo.com	52	8	PENDING
266	Theresa	Davis	jasmindiaz@gmail.com	93	7	PENDING
267	Devin	Morris	virginiakelly@hotmail.com	33	2	REJECTED
268	Corey	Woods	wolfekaren@yahoo.com	55	1	PENDING
269	Deborah	Ruiz	nelsonrobert@gmail.com	64	2	REJECTED
270	James	Moore	syates@hotmail.com	80	7	PENDING
271	Amanda	Morris	ncarter@hotmail.com	21	5	PAID
272	Cynthia	Farmer	tferguson@gmail.com	28	\N	PENDING
273	Carl	Lewis	william66@hotmail.com	58	6	PENDING
274	Angela	Coleman	ejohnson@hotmail.com	57	7	PAID
275	Frank	Krause	andrewatkins@yahoo.com	24	8	PENDING
276	Nicolas	Coleman	jamesmiller@yahoo.com	82	7	PAID
277	Christine	Jenkins	rickytucker@yahoo.com	27	1	PAID
278	Sarah	Gutierrez	deannafischer@gmail.com	52	2	PAID
279	Michael	Hunter	kendraroberts@gmail.com	25	7	PENDING
280	Emily	Raymond	victoria22@gmail.com	59	\N	PENDING
281	Caitlin	Hoffman	samuelharmon@gmail.com	24	7	PAID
282	Matthew	Rice	qwatson@gmail.com	74	\N	REJECTED
283	Emily	Harris	michaelacosta@hotmail.com	43	5	PAID
284	Aaron	Martinez	norrismiranda@hotmail.com	19	5	PAID
285	Belinda	Mata	evanssergio@yahoo.com	44	1	REJECTED
286	Jodi	Duarte	juanhamilton@yahoo.com	60	\N	PENDING
287	Stacey	Wong	jamie02@yahoo.com	70	3	PENDING
288	Brandon	Hughes	jacob15@gmail.com	91	6	REJECTED
289	Rachel	Mills	hking@yahoo.com	31	2	PAID
290	Paul	Brown	amy25@yahoo.com	27	8	PENDING
291	Vincent	Greene	johnstondiana@gmail.com	31	6	REJECTED
292	Lindsey	Knight	stevenscolleen@yahoo.com	27	4	PAID
293	Steven	Ramirez	lmalone@gmail.com	53	2	PENDING
294	Sean	Curry	laurenjohnson@yahoo.com	60	5	REJECTED
295	Maria	Woodward	iwhite@hotmail.com	36	6	REJECTED
296	Patrick	Mathews	anthony24@yahoo.com	33	\N	PENDING
297	Andrew	Tanner	qmullins@hotmail.com	82	6	PENDING
298	Jordan	Murillo	fcombs@gmail.com	75	5	PAID
299	Victoria	Turner	maria36@gmail.com	20	\N	REJECTED
300	Angela	Smith	mcdonaldjodi@yahoo.com	77	5	REJECTED
301	William	Phelps	moralesdavid@yahoo.com	59	3	PAID
302	Christopher	Hayes	deancheryl@yahoo.com	33	\N	PENDING
303	Danielle	Kelly	anne28@gmail.com	94	6	PAID
304	Rebekah	Smith	estone@hotmail.com	55	2	PENDING
305	Sarah	Benjamin	steven27@gmail.com	18	\N	PAID
306	Robert	Schultz	drodgers@yahoo.com	57	8	PENDING
307	Darryl	Oliver	melvin19@hotmail.com	43	3	PENDING
308	Alyssa	Finley	martingary@yahoo.com	94	5	PENDING
309	Lisa	Keith	kathleenlopez@gmail.com	38	\N	PENDING
310	Monica	Smith	williamestes@hotmail.com	41	5	REJECTED
311	Crystal	Burgess	taylorpeter@hotmail.com	37	2	PAID
312	Henry	Wall	wmerritt@hotmail.com	89	2	PAID
313	Brittany	Gomez	keith40@yahoo.com	55	8	PENDING
314	Kenneth	Bell	maryhogan@yahoo.com	49	3	PENDING
315	Daniel	Simmons	hknapp@yahoo.com	60	6	REJECTED
316	Christine	Santana	joshua28@gmail.com	80	1	PENDING
317	Anne	Russell	omiller@hotmail.com	45	5	REJECTED
318	Jenna	Robertson	alanvazquez@yahoo.com	21	7	PAID
319	Brandy	Schneider	combskevin@yahoo.com	70	1	PENDING
320	Robert	Stephens	stonekathleen@gmail.com	30	5	REJECTED
321	Jeffrey	Brown	cindy33@gmail.com	47	3	REJECTED
322	George	Blair	justin62@gmail.com	60	2	REJECTED
323	Tamara	Davis	andersonaaron@yahoo.com	44	4	PAID
324	Nicholas	Haley	smithmichael@gmail.com	54	7	PAID
325	Ryan	James	sandra90@yahoo.com	20	2	PENDING
326	Emily	White	vsmith@hotmail.com	34	\N	REJECTED
327	Joanna	Pearson	paulwebb@gmail.com	19	4	PAID
328	Marcia	Skinner	austinkim@gmail.com	47	4	PAID
329	Steven	Callahan	armstrongdouglas@gmail.com	75	5	PENDING
330	Joshua	Cline	harrishannah@yahoo.com	96	7	REJECTED
331	Amber	Morton	sgordon@yahoo.com	64	\N	PAID
332	Allison	Liu	rrobinson@gmail.com	61	7	REJECTED
333	Karen	Allen	heather66@yahoo.com	19	\N	PAID
334	Kristen	Rodriguez	laceyjohnston@gmail.com	63	8	PENDING
335	Bobby	Rogers	maryrivera@gmail.com	58	\N	REJECTED
336	Allen	Johnson	fieldssusan@gmail.com	55	5	PAID
337	Nicole	Wallace	candicemoreno@gmail.com	38	\N	PAID
338	Kyle	Davis	johnwise@hotmail.com	54	8	PENDING
339	Miguel	Austin	thomasadam@gmail.com	41	6	REJECTED
340	Nicholas	Jones	parkersusan@yahoo.com	86	5	PENDING
341	Katrina	Welch	psmith@yahoo.com	19	\N	PAID
342	Sandra	Walker	iclay@hotmail.com	61	5	REJECTED
343	Brian	Espinoza	flopez@hotmail.com	50	8	PENDING
344	Denise	Martin	kristina00@yahoo.com	42	\N	REJECTED
345	Karina	Sutton	baxterbradley@gmail.com	35	8	PENDING
346	Stephanie	Myers	jramos@gmail.com	68	\N	PAID
347	Michael	Lane	donna42@yahoo.com	19	6	PENDING
348	Christine	Elliott	vbell@hotmail.com	45	2	REJECTED
349	Kristin	Chung	vwatkins@yahoo.com	43	5	PENDING
350	Melissa	Doyle	qhoward@gmail.com	92	5	REJECTED
351	Leslie	Parker	turnersherri@yahoo.com	48	7	PAID
352	Robin	Burke	mlewis@gmail.com	27	1	REJECTED
353	Jeffrey	Smith	mallory08@hotmail.com	30	7	PAID
354	Corey	Harris	wagnerjames@hotmail.com	77	2	REJECTED
355	Johnny	Hall	chris73@gmail.com	22	7	PENDING
356	Mary	King	hodgejennifer@hotmail.com	100	5	PENDING
357	Katie	Payne	shubbard@hotmail.com	46	2	PENDING
358	Alexis	Garcia	patrickjohnson@hotmail.com	19	4	PAID
359	Timothy	Weaver	eshelton@yahoo.com	48	\N	REJECTED
360	Danny	Boone	anathompson@hotmail.com	23	3	PAID
361	Jessica	Powell	tammy25@yahoo.com	43	5	REJECTED
362	Robert	Goodman	webbmelissa@hotmail.com	71	5	REJECTED
363	Terri	Scott	meyersmichael@yahoo.com	100	2	PENDING
364	Erica	Reed	taratodd@hotmail.com	32	7	REJECTED
365	Kenneth	Frey	zvaldez@hotmail.com	46	6	PAID
366	Tracy	Jackson	william25@yahoo.com	33	6	PENDING
367	Roy	Peterson	alancarr@gmail.com	39	2	PAID
368	William	Lopez	qbennett@gmail.com	74	6	REJECTED
369	Zachary	Bryant	haley00@gmail.com	29	2	REJECTED
370	Brandon	Romero	kirkdoyle@hotmail.com	80	6	PAID
371	Heather	Bailey	bhendricks@hotmail.com	60	8	PENDING
372	Kenneth	Wolfe	bpatrick@yahoo.com	48	5	PAID
373	Ryan	Brooks	hmartin@yahoo.com	32	7	PAID
374	Linda	Lang	johnsonashley@hotmail.com	34	3	REJECTED
375	Brittany	Snow	nancyreed@hotmail.com	35	4	PAID
376	David	Smith	scott04@gmail.com	88	8	PENDING
377	Brian	Hamilton	sandy92@hotmail.com	69	3	REJECTED
378	Joanne	Love	millspatricia@gmail.com	51	3	REJECTED
379	Misty	Palmer	maria36@gmail.com	33	5	REJECTED
380	Julie	Williams	adrianmiller@yahoo.com	59	7	PENDING
381	Tracey	Wells	daniel08@yahoo.com	48	5	PAID
382	Michael	Casey	amber41@gmail.com	31	1	REJECTED
383	Jeremy	Cruz	simmonschristian@hotmail.com	82	\N	REJECTED
384	Matthew	Reed	michaelgraham@gmail.com	22	7	REJECTED
385	Jaclyn	Warner	cdunn@hotmail.com	71	2	PENDING
386	Charles	Garcia	davidalexander@hotmail.com	53	8	PENDING
387	Leslie	Mejia	xgarrett@gmail.com	60	1	PAID
388	Nathan	Boyd	daniel86@gmail.com	56	8	PENDING
389	Frances	Robertson	daniellesantiago@hotmail.com	65	4	PAID
390	Melissa	Reynolds	uponce@gmail.com	48	6	PAID
391	Brenda	Hughes	oking@gmail.com	59	8	PENDING
392	Gabriel	Bell	jessicajones@yahoo.com	43	\N	PENDING
393	Eric	Ortiz	joneskristen@gmail.com	29	4	PAID
394	Cheryl	Smith	tracy41@gmail.com	92	8	PENDING
395	Jeffrey	Ruiz	brenda19@gmail.com	41	5	REJECTED
396	Dustin	Wolfe	jackie18@yahoo.com	54	7	PENDING
397	Zachary	Smith	blackerika@gmail.com	45	2	REJECTED
398	Victor	Phillips	theresa80@gmail.com	43	1	REJECTED
399	Jennifer	Flores	hmathis@hotmail.com	48	4	PAID
400	Michael	Bullock	ryan52@hotmail.com	28	2	PAID
401	Melissa	Leon	zandrade@yahoo.com	40	5	PAID
402	Angela	Rogers	reneediaz@yahoo.com	98	2	PAID
\.


--
-- Data for Name: teachers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teachers (id, firstname, lastname, email) FROM stdin;
1	Crystal	Bolton	brendan36@yahoo.com
2	Candice	Oneal	leah38@gmail.com
3	Jerome	Ryan	sarah84@gmail.com
4	Jessica	Tanner	james54@gmail.com
5	Jane	Smith	brooksjoseph@yahoo.com
\.


--
-- Name: bank_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bank_accounts_id_seq', 50, true);


--
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_id_seq', 8, true);


--
-- Name: students_copy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.students_copy_id_seq', 402, true);


--
-- Name: students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.students_id_seq', 200, true);


--
-- Name: teachers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teachers_id_seq', 5, true);


--
-- Name: bank_accounts bank_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: students_copy students_copy_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students_copy
    ADD CONSTRAINT students_copy_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: courses_description; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_description ON public.courses USING gin (to_tsvector('english'::regconfig, description)) WITH (fastupdate='true');


--
-- PostgreSQL database dump complete
--

\unrestrict TSOfPaWL4h1zMXuDMt8f9ARco1vxXgmhTGNHHShAYOE86gZaUgBHO6LopHLDz0G

